"""почему он говорит что site нет в user_info

Revision ID: 841a0dfd9ae6
Revises: 
Create Date: 2023-09-19 00:26:16.585380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '841a0dfd9ae6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('card')
    op.drop_table('session')
    op.drop_table('snils')
    op.drop_table('auth')
    op.drop_table('user_info')
    op.drop_table('transport')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transport',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('transport_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('transport_num', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='transport_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('user_info',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('user_info_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('phone', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('user_type', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('mail', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='user_info_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('auth',
    sa.Column('login', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('user_info', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_info'], ['user_info.id'], name='auth_user_info_fkey'),
    sa.PrimaryKeyConstraint('login', name='auth_pkey')
    )
    op.create_table('snils',
    sa.Column('snils_num', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='snils_user_id_fkey'),
    sa.PrimaryKeyConstraint('snils_num', name='snils_pkey')
    )
    op.create_table('session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('start_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('end_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('conductor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('transport_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['conductor_id'], ['user.id'], name='session_conductor_id_fkey'),
    sa.ForeignKeyConstraint(['transport_id'], ['transport.id'], name='session_transport_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='session_pkey')
    )
    op.create_table('card',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('expire_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('card_num', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='card_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='card_pkey')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('user_info', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('surname', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('patronymic', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_info'], ['user_info.id'], name='user_user_info_fkey'),
    sa.PrimaryKeyConstraint('id', name='user_pkey')
    )
    # ### end Alembic commands ###
